from openai import OpenAI
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()

# Access the API key from the environment variable
api_key = os.getenv('API_KEY')

# Store the api key...
client = OpenAI(api_key=api_key)


# Interactive function for I/O
def chatbot(user_input):
    """
    This function takes in user input then uses the OpenAI API key to output the response generated by
    the gpt-3.5-turbo model.
    :param user_input: Input given by the user (a string).
    :return: Response from OpenAI API.
    """
    system_bias = "You're a informative AI chatbot that specialises in data science, visualisation and analytics."
    # Message from user input given to the API
    messages = [
        {"role": "system", "content": system_bias},
        {"role": "user", "content": user_input}
    ]

    completion = client.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=messages
    )

    return completion.choices[0].message.content
